########programacion de encendido automatico luces efecto amanecer y atardecer#####


############a las 15:45############
- alias: amanecer acuario
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.onledacuario
      from: 'off'
      to: 'on' 
  action:
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 64]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 128]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 192]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 255]     
   - delay: '00:01:00'   
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [88, 33, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [162, 71, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 71, 71]
   - delay: '00:01:00'   
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 162, 71] 
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 218, 108]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 255, 145]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 255, 255]
   - service: input_boolean.turn_off
     data:
      entity_id: input_boolean.onledacuario      
      
############a las 18:00############   
- alias: on blue acuario
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.onledacuario2
      from: 'off'
      to: 'on' 
  action:
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [192, 192, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [128, 128, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [64, 64, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 255]
   - service: input_boolean.turn_off
     data:
      entity_id: input_boolean.onledacuario2   

############a las 20:00############   
- alias: on red acuario
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.onledacuario5
      from: 'off'
      to: 'on' 
  action:
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [126, 0, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 0, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 0, 126]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 0, 0]
   - service: input_boolean.turn_off
     data:
      entity_id: input_boolean.onledacuario5
############a las 21:50############        
- alias: anochecer acuario
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.onledacuario3
      from: 'off'
      to: 'on' 
  action:
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [64, 64, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [128, 128, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [192, 192, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [255, 255, 255]
   - delay: '00:20:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [192, 192, 255]
   - delay: '00:05:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [128, 128, 255]
   - delay: '00:05:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [64, 64, 255]
   - delay: '00:01:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 255]
   - service: input_boolean.turn_off
     data:
      entity_id: input_boolean.onledacuario3
      
############a las 23:00############        
- alias: atardecer acuario
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.onledacuario4
      from: 'off'
      to: 'on' 
  action:
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 192]
   - delay: '00:10:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 128]
   - delay: '00:20:00'
   - service: light.turn_on
     data:
      entity_id: light.acuario
      rgb_color: [0, 0, 64]
   - delay: '00:30:00'
   - service: light.turn_off
     data:
      entity_id: light.acuario
   - service: input_boolean.turn_off
     data:
      entity_id: input_boolean.onledacuario4