


#####medidor de consumo general casa######
- platform: template
  sensors:
   consumo_actual_casa:
     friendly_name: "Consumo actual casa"
     value_template: "{{ (( states('sensor.consumo_actual')|float ) / 1000 )|round(2) }}"   
     unit_of_measurement: 'kW'
     device_class: "energy"


- platform: template
  sensors:
   consumo_total_casa:
     friendly_name: "Consumo total casa"
     value_template: "{{ (( states('sensor.consumo_total')|float ) / 100 )|round(2) }}"   
     unit_of_measurement: 'kWh'
     device_class: "energy"

- platform: template
  sensors:
   consumo_mes_energy:
     friendly_name: "Consumo mes energy"
     value_template: "{{ (( states('var.luz_energia_mensual')|float ) )|round(2) }}"   
     unit_of_measurement: 'kWh'
     device_class: "energy"


##############enchufe medidor consumo lavadora

- platform: template
  sensors:
    lavadora_estado:
     friendly_name: "Lavadora estado"
     value_template: >
       {% if states("sensor.enchufe_lavadora_potencia")|float == 0  %}
         Off
       {% elif states("sensor.enchufe_lavadora_potencia")|float <= 8 %}
         Standby
       {% else %}
         Drying
       {% endif %}
     icon_template: >
       {% if states("switch.enchufe_lavadora") == "off"  %}
       mdi:tumble-dryer-alert
       {% elif states("sensor.enchufe_lavadora_potencia")|float <= 2  %}
       mdi:tumble-dryer-off
       {% else %}
       mdi:tumble-dryer
       {% endif %}