- platform: template
  sensors:
    vacuum_status:
      friendly_name: Estado
      value_template: 'Estado: {{ states.vacuum.geoffrey.attributes.status }}'
      icon_template: >
        {% set val =  states.vacuum.geoffrey.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Velocidad ventilador
      value_template: 'Modo: {{ states.vacuum.geoffrey.attributes.fan_speed }}'
      icon_template: 'mdi:speedometer'
    vacuum_battery:
      friendly_name: Bateria
      value_template: 'Bateria: {{ states.vacuum.geoffrey.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: '{{ states.vacuum.geoffrey.attributes.battery_icon }}'
    vacuum_cleaning_time:
      friendly_name: Ultimo ciclo
      value_template: '{{ states.vacuum.geoffrey.attributes.s_time }}'
      unit_of_measurement: 'Min.'
      icon_template: 'mdi:timer'
    vacuum_cleaned_area:
      friendly_name: Area ultimo ciclo
      unit_of_measurement: 'm ²'
      value_template: '{{ states.vacuum.geoffrey.attributes.s_area }}'
      icon_template: 'mdi:ruler'
    vacuum_operation:
      friendly_name: Estado
      value_template: 'Estado'
    vacuum_accessories:
      friendly_name: Mantenimiento
      value_template: 'Mantenimiento'  
    vacuum_cleaner_error_sensor:
      friendly_name: Error
      value_template: >-
        {% if states.vacuum.geoffrey.attributes.error is defined %}
          {{states.vacuum.geoffrey.attributes.error}}
        {% else %}
          No Error
        {% endif %}